name: Versioning

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    
    - name: Configure committer
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - run: npm install
        
    - run: npm run version

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
