name: PR to Versioning
on: workflow_dispatch
jobs:
  create-pull-request:
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
